version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
        SQL_SERVER: "db"
        SQL_DATABASE: "CP3DevOps"
        SQL_USER: "sa"
        SQL_PASSWORD: "@Senha123"
    depends_on:
      - db
  db:
    image: "advitec/mssql-server-windows-developer"
    environment:
      SA_PASSWORD: "@Senha123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:C:\db
volumes:
  db-data:
